import type { Activity, Comment, LiveMatch, Match, MatchMode, Player } from "./types";
import { isCompetitive } from "./types";

export const players: Player[] = [
  {
    id: "p1",
    username: "felix_fr",
    fullName: "Félix Lebrun",
    country: "France",
    countryFlag: "🇫🇷",
    city: "Montpellier",
    club: "Montpellier TT",
    avatar: "🦊",
    rating: 2812,
    peakRating: 2845,
    rankedWins: 218,
    rankedLosses: 41,
    casualWins: 64,
    casualLosses: 22,
    followers: 18420,
    bio: "Pongiste pro. Service court, attaque rapide.",
  },
  {
    id: "p2",
    username: "alexis_lebrun",
    fullName: "Alexis Lebrun",
    country: "France",
    countryFlag: "🇫🇷",
    city: "Montpellier",
    club: "Montpellier TT",
    avatar: "🐺",
    rating: 2778,
    peakRating: 2790,
    rankedWins: 195,
    rankedLosses: 38,
    casualWins: 51,
    casualLosses: 19,
    followers: 14210,
  },
  {
    id: "p3",
    username: "wang_chuqin",
    fullName: "Wang Chuqin",
    country: "Chine",
    countryFlag: "🇨🇳",
    city: "Pékin",
    avatar: "🐉",
    rating: 2901,
    peakRating: 2912,
    rankedWins: 312,
    rankedLosses: 27,
    casualWins: 88,
    casualLosses: 14,
    followers: 92110,
  },
  {
    id: "p4",
    username: "tomokazu",
    fullName: "Tomokazu Harimoto",
    country: "Japon",
    countryFlag: "🇯🇵",
    city: "Tokyo",
    avatar: "🦅",
    rating: 2802,
    peakRating: 2815,
    rankedWins: 240,
    rankedLosses: 44,
    casualWins: 70,
    casualLosses: 25,
    followers: 31040,
  },
  {
    id: "p5",
    username: "leon_amateur",
    fullName: "Léon Le Calvez",
    country: "France",
    countryFlag: "🇫🇷",
    city: "Paris",
    club: "Paris 13 TT",
    avatar: "🐧",
    rating: 1487,
    peakRating: 1502,
    rankedWins: 34,
    rankedLosses: 29,
    casualWins: 52,
    casualLosses: 47,
    followers: 12,
    bio: "Coup droit topspin, revers bloc. En progression.",
  },
  {
    id: "p6",
    username: "marie_smash",
    fullName: "Marie Dubois",
    country: "France",
    countryFlag: "🇫🇷",
    city: "Lyon",
    club: "Lyon TT",
    avatar: "🦋",
    rating: 1820,
    peakRating: 1840,
    rankedWins: 88,
    rankedLosses: 51,
    casualWins: 33,
    casualLosses: 30,
    followers: 240,
  },
  {
    id: "p7",
    username: "diaz_es",
    fullName: "Carlos Diaz",
    country: "Espagne",
    countryFlag: "🇪🇸",
    city: "Barcelone",
    avatar: "🐂",
    rating: 1965,
    peakRating: 1980,
    rankedWins: 110,
    rankedLosses: 60,
    casualWins: 41,
    casualLosses: 33,
    followers: 540,
  },
  {
    id: "p8",
    username: "sofia_de",
    fullName: "Sofia Müller",
    country: "Allemagne",
    countryFlag: "🇩🇪",
    city: "Berlin",
    avatar: "🦌",
    rating: 2040,
    peakRating: 2055,
    rankedWins: 132,
    rankedLosses: 70,
    casualWins: 48,
    casualLosses: 36,
    followers: 880,
  },
];

export const CURRENT_USER_ID = "p5";
export const CURRENT_USER_FRIENDS = new Set(["p1", "p2", "p6", "p7"]);

export const matches: Match[] = [
  {
    id: "m1",
    player1Id: "p5",
    player2Id: "p6",
    sets: [
      { p1: 11, p2: 8 },
      { p1: 9, p2: 11 },
      { p1: 11, p2: 7 },
      { p1: 11, p2: 9 },
    ],
    winnerId: "p5",
    ratingChange: { p1: 18, p2: -18 },
    playedAt: "2026-04-28T19:30:00Z",
    venue: "Paris 13 TT",
    format: "BO5",
    mode: "ranked",
  },
  {
    id: "m2",
    player1Id: "p1",
    player2Id: "p3",
    sets: [
      { p1: 11, p2: 9 },
      { p1: 8, p2: 11 },
      { p1: 11, p2: 13 },
      { p1: 11, p2: 6 },
      { p1: 9, p2: 11 },
    ],
    winnerId: "p3",
    ratingChange: { p1: -8, p2: 8 },
    playedAt: "2026-04-27T16:00:00Z",
    venue: "WTT Champions",
    format: "BO5",
    mode: "tournament",
  },
  {
    id: "m3",
    player1Id: "p7",
    player2Id: "p8",
    sets: [
      { p1: 11, p2: 6 },
      { p1: 11, p2: 9 },
      { p1: 11, p2: 8 },
    ],
    winnerId: "p7",
    ratingChange: { p1: 14, p2: -14 },
    playedAt: "2026-04-28T11:00:00Z",
    format: "BO5",
    mode: "ranked",
  },
  {
    id: "m4",
    player1Id: "p5",
    player2Id: "p7",
    sets: [
      { p1: 6, p2: 11 },
      { p1: 8, p2: 11 },
      { p1: 7, p2: 11 },
    ],
    winnerId: "p7",
    ratingChange: { p1: -22, p2: 22 },
    playedAt: "2026-04-22T18:00:00Z",
    format: "BO5",
    mode: "ranked",
  },
  {
    id: "m5",
    player1Id: "p5",
    player2Id: "p2",
    sets: [
      { p1: 8, p2: 11 },
      { p1: 11, p2: 9 },
      { p1: 6, p2: 11 },
    ],
    winnerId: "p2",
    playedAt: "2026-04-25T20:00:00Z",
    venue: "Paris 13 TT — Open Day",
    format: "BO5",
    mode: "casual",
  },
  {
    id: "m6",
    player1Id: "p3",
    player2Id: "p4",
    sets: [
      { p1: 11, p2: 7 },
      { p1: 11, p2: 9 },
      { p1: 8, p2: 11 },
      { p1: 11, p2: 6 },
    ],
    winnerId: "p3",
    ratingChange: { p1: 5, p2: -5 },
    playedAt: "2026-04-20T14:00:00Z",
    venue: "WTT Finals",
    format: "BO7",
    mode: "tournament",
  },
  {
    id: "m7",
    player1Id: "p1",
    player2Id: "p2",
    sets: [
      { p1: 11, p2: 9 },
      { p1: 9, p2: 11 },
      { p1: 12, p2: 10 },
    ],
    winnerId: "p1",
    playedAt: "2026-04-30T19:00:00Z",
    venue: "Montpellier TT",
    format: "BO5",
    mode: "casual",
  },
  {
    id: "m8",
    player1Id: "p5",
    player2Id: "p8",
    sets: [
      { p1: 11, p2: 9 },
      { p1: 7, p2: 11 },
      { p1: 11, p2: 13 },
    ],
    winnerId: "p8",
    ratingChange: { p1: -15, p2: 15 },
    playedAt: "2026-04-24T18:00:00Z",
    venue: "Paris 13 TT",
    format: "BO5",
    mode: "ranked",
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    kind: "match",
    playerId: "p5",
    matchId: "m1",
    createdAt: "2026-04-28T20:00:00Z",
    likes: 7,
    comments: 2,
  },
  {
    id: "a2",
    kind: "training",
    playerId: "p5",
    trainingMinutes: 90,
    trainingTitle: "Service + 3e balle (panier)",
    createdAt: "2026-04-27T18:30:00Z",
    likes: 4,
    comments: 1,
  },
  {
    id: "a3",
    kind: "match",
    playerId: "p1",
    matchId: "m2",
    createdAt: "2026-04-27T17:00:00Z",
    likes: 1820,
    comments: 134,
  },
  {
    id: "a4",
    kind: "achievement",
    playerId: "p5",
    achievementTitle: "Premier 1500 ELO atteint 🎉",
    createdAt: "2026-04-26T22:10:00Z",
    likes: 18,
    comments: 5,
  },
  {
    id: "a5",
    kind: "training",
    playerId: "p6",
    trainingMinutes: 60,
    trainingTitle: "Footwork latéral",
    createdAt: "2026-04-26T08:00:00Z",
    likes: 12,
    comments: 0,
  },
  {
    id: "a6",
    kind: "match",
    playerId: "p7",
    matchId: "m3",
    createdAt: "2026-04-28T11:30:00Z",
    likes: 22,
    comments: 3,
  },
  {
    id: "a7",
    kind: "match",
    playerId: "p5",
    matchId: "m5",
    createdAt: "2026-04-25T20:30:00Z",
    likes: 9,
    comments: 4,
  },
  // ── new entries ─────────────────────────────────────────────────
  {
    id: "a8",
    kind: "tournament",
    playerId: "p6",
    createdAt: "2026-04-29T09:00:00Z",
    tournamentTitle: "Open de Paris — Printemps 2026",
    tournamentDate: "2026-05-18",
    tournamentVenue: "Paris 13 TT",
    tournamentParticipants: 34,
    tournamentMaxParticipants: 64,
    tournamentPrize: "Classement officiel + coupes",
    likes: 45,
    comments: 12,
  },
  {
    id: "a9",
    kind: "achievement",
    playerId: "p3",
    achievementTitle: "Classement mondial n°1 — WTT 2026 🌍",
    createdAt: "2026-04-29T15:00:00Z",
    likes: 2840,
    comments: 412,
  },
  {
    id: "a10",
    kind: "club_announce",
    playerId: "p5",
    createdAt: "2026-04-30T10:00:00Z",
    announceTitle: "Soirée portes ouvertes — vendredi 2 mai",
    announceBody:
      "Paris 13 TT ouvre ses portes vendredi soir de 19h à 23h. Tables libres, débutants bienvenus. Amenez vos raquettes !",
    likes: 31,
    comments: 8,
  },
  {
    id: "a11",
    kind: "match",
    playerId: "p8",
    matchId: "m3",
    createdAt: "2026-04-28T12:00:00Z",
    likes: 8,
    comments: 1,
  },
  {
    id: "a12",
    kind: "training",
    playerId: "p1",
    trainingMinutes: 120,
    trainingTitle: "Préparation physique + multiballes",
    createdAt: "2026-04-29T08:00:00Z",
    likes: 340,
    comments: 18,
  },
  {
    id: "a13",
    kind: "tournament",
    playerId: "p6",
    createdAt: "2026-04-24T14:00:00Z",
    tournamentTitle: "Lyon Open Juniors & Seniors",
    tournamentDate: "2026-05-31",
    tournamentVenue: "Lyon TT — Salle Bellecour",
    tournamentParticipants: 12,
    tournamentMaxParticipants: 48,
    tournamentPrize: "500 € + points FFTT",
    likes: 29,
    comments: 7,
  },
  {
    id: "a14",
    kind: "match",
    playerId: "p3",
    matchId: "m6",
    createdAt: "2026-04-20T15:00:00Z",
    likes: 1540,
    comments: 88,
  },
  {
    id: "a15",
    kind: "achievement",
    playerId: "p5",
    achievementTitle: "10 matchs consécutifs enregistrés 🏓",
    createdAt: "2026-04-23T21:00:00Z",
    likes: 14,
    comments: 3,
  },
  {
    id: "a16",
    kind: "training",
    playerId: "p6",
    trainingMinutes: 75,
    trainingTitle: "Smash + revers topspin",
    createdAt: "2026-04-22T17:00:00Z",
    likes: 19,
    comments: 2,
  },
  {
    id: "a17",
    kind: "follow",
    playerId: "p5",
    targetPlayerId: "p1",
    createdAt: "2026-04-27T09:00:00Z",
    likes: 3,
    comments: 0,
  },
  {
    id: "a18",
    kind: "match",
    playerId: "p1",
    matchId: "m7",
    createdAt: "2026-04-30T20:00:00Z",
    likes: 620,
    comments: 41,
  },
  {
    id: "a19",
    kind: "club_announce",
    playerId: "p6",
    createdAt: "2026-04-21T09:00:00Z",
    announceTitle: "Nouveau coach certifié chez Lyon TT",
    announceBody:
      "On accueille Marco Bianchi (ex-entraîneur national italien) pour des stages intensifs à partir de mai. Inscriptions ouvertes !",
    likes: 67,
    comments: 14,
  },
  {
    id: "a20",
    kind: "training",
    playerId: "p3",
    trainingMinutes: 180,
    trainingTitle: "Camp d'entraînement — prépa WTT",
    createdAt: "2026-04-18T10:00:00Z",
    likes: 980,
    comments: 56,
  },
  {
    id: "a21",
    kind: "match",
    playerId: "p5",
    matchId: "m8",
    createdAt: "2026-04-24T19:00:00Z",
    likes: 6,
    comments: 2,
  },
  {
    id: "a22",
    kind: "tournament",
    playerId: "p8",
    createdAt: "2026-04-17T11:00:00Z",
    tournamentTitle: "Berlin International Open 2026",
    tournamentDate: "2026-06-07",
    tournamentVenue: "Sporthalle Tempelhof, Berlin",
    tournamentParticipants: 55,
    tournamentMaxParticipants: 128,
    tournamentPrize: "WTT ranking points",
    likes: 112,
    comments: 23,
  },
  {
    id: "a23",
    kind: "achievement",
    playerId: "p7",
    achievementTitle: "50 victoires classées franchies 🎯",
    createdAt: "2026-04-19T20:00:00Z",
    likes: 88,
    comments: 11,
  },
  {
    id: "a24",
    kind: "training",
    playerId: "p4",
    trainingMinutes: 90,
    trainingTitle: "Analyse vidéo + exercices de service",
    createdAt: "2026-04-16T09:00:00Z",
    likes: 210,
    comments: 9,
  },
  {
    id: "a25",
    kind: "match",
    playerId: "p2",
    matchId: "m7",
    createdAt: "2026-04-30T20:30:00Z",
    likes: 480,
    comments: 33,
  },
];

export const comments: Comment[] = [
  { id: "c1",  activityId: "a1",  playerId: "p6", text: "Belle victoire ! 🏓",                    createdAt: "2026-04-28T20:30:00Z" },
  { id: "c2",  activityId: "a1",  playerId: "p7", text: "Bien joué @leon_amateur !",              createdAt: "2026-04-28T21:00:00Z" },
  { id: "c3",  activityId: "a3",  playerId: "p5", text: "Incroyable match 👏",                   createdAt: "2026-04-27T17:30:00Z" },
  { id: "c4",  activityId: "a3",  playerId: "p2", text: "Revanche bientôt 😤",                   createdAt: "2026-04-27T18:00:00Z" },
  { id: "c5",  activityId: "a4",  playerId: "p6", text: "Bravo Léon ! Prochain objectif 1600 ?", createdAt: "2026-04-26T22:30:00Z" },
  { id: "c6",  activityId: "a8",  playerId: "p5", text: "Je m'inscris ! 🙋",                     createdAt: "2026-04-29T09:30:00Z" },
  { id: "c7",  activityId: "a8",  playerId: "p7", text: "Paris 13 TT toujours aux avant-postes", createdAt: "2026-04-29T10:00:00Z" },
  { id: "c8",  activityId: "a9",  playerId: "p1", text: "Méritée ! Longue règne 👑",             createdAt: "2026-04-29T15:20:00Z" },
  { id: "c9",  activityId: "a9",  playerId: "p5", text: "Un monstre 🐉",                          createdAt: "2026-04-29T16:00:00Z" },
  { id: "c10", activityId: "a10", playerId: "p6", text: "On viendra depuis Lyon ! 🚄",            createdAt: "2026-04-30T10:30:00Z" },
  { id: "c11", activityId: "a18", playerId: "p5", text: "Grande forme en ce moment @felix_fr !",  createdAt: "2026-04-30T20:15:00Z" },
  { id: "c12", activityId: "a21", playerId: "p6", text: "Courage, la revanche approche 💪",       createdAt: "2026-04-24T19:30:00Z" },
];

export const liveMatches: LiveMatch[] = [
  {
    id: "lm1",
    player1Id: "p3",
    player2Id: "p4",
    sets: [
      { p1: 11, p2: 8 },
      { p1: 9, p2: 11 },
    ],
    currentSet: { p1: 7, p2: 5 },
    format: "BO5",
    viewers: 4280,
  },
  {
    id: "lm2",
    player1Id: "p2",
    player2Id: "p8",
    sets: [{ p1: 11, p2: 6 }],
    currentSet: { p1: 4, p2: 3 },
    format: "BO5",
    viewers: 612,
  },
];

export function getPlayer(id: string): Player | undefined {
  return players.find((p) => p.id === id);
}

export function getMatch(id: string): Match | undefined {
  return matches.find((m) => m.id === id);
}

export function getMatchesForPlayer(
  id: string,
  filter: "all" | "competitive" | "casual" = "all",
): Match[] {
  return matches
    .filter((m) => m.player1Id === id || m.player2Id === id)
    .filter((m) => {
      if (filter === "all") return true;
      if (filter === "casual") return m.mode === "casual";
      return isCompetitive(m.mode);
    })
    .sort((a, b) => b.playedAt.localeCompare(a.playedAt));
}

export function getMatchModeLabel(mode: MatchMode): string {
  if (mode === "tournament") return "Tournoi";
  if (mode === "ranked") return "Classé";
  return "Amical";
}

export function getActivitiesSorted(): Activity[] {
  return [...activities].sort((a, b) =>
    b.createdAt.localeCompare(a.createdAt),
  );
}

export function getCommentsForActivity(activityId: string) {
  return comments.filter((c) => c.activityId === activityId);
}

export function getLeaderboard(): Player[] {
  return [...players].sort((a, b) => b.rating - a.rating);
}
